### Get All Data users
GET http://localhost:5000/Users


### Get Single Data user
GET http://localhost:5000/Users/645a6338688cadf4577d3bd8

### Create user
POST http://localhost:5000/Users
Content-Type: application/json

{
    "name" : "Ramdani",
    "email" : "ramdani@gmail.com",
    "gender": "Male"
}

### Update user
PATCH  http://localhost:5000/Users/645a6338688cadf4577d3bd8
Content-Type: application/json

{
    "name" : "Ramdani updated",
    "email" : "ramdani@gmail.com",
    "gender": "Male updated"
}

### Delete user
DELETE  http://localhost:5000/Users/645a6338688cadf4577d3bd8
